# Generated by Django 6.1 on 2026-08-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitante_apellido',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitante_nombre',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
