# Generated by Django 6.1 on 2026-08-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_prestamo_solicitante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='solicitante_apellido',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='solicitante_nombre',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
