# Generated by Django 6.1 on 2026-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_prestamo_solicitante_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitante_apellido',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitante_nombre',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
